ASM:=../../bin/asrv32im
ACSE:=../../bin/acse

SRC=$(wildcard *.src)
OBJS=$(patsubst %.src,%.o,$(SRC))

# This is used to ensure sources are recompiled when ACSE changes
ifeq ($(OS), Windows_NT)
ACSE_FILE:=$(ACSE).exe
else
ACSE_FILE:=$(ACSE)
endif

.PHONY: test
ifeq (,$(wildcard _NO_TEST_))
# the '_NO_TEST_' file does not exist
test: $(OBJS)
else
# the '_NO_TEST_' file does exist
test:
	@echo 'info: tests in directory "$(notdir $(shell pwd))" skipped'
endif

%.o: %.s
	$(ASM) $< -o $@

.PRECIOUS: %.s
%.s: %.src $(ACSE_FILE)
	$(ACSE) $< -o $@

.PHONY: clean 
clean :
	rm -f *.log *.s *.o
